Seo.Route/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Seo.Route.Controllers
{
    public class BaseController : Controller
    {
        public BaseController()
        { }
        protected virtual ActionResult RedirectToReferrer()
        {
            if (Request.UrlReferrer != null && string.IsNullOrEmpty(Request.UrlReferrer.ToString()))
            {
                return Redirect(Request.UrlReferrer.ToString());
            }

            return RedirectToRoute("HomePage");
        }
    }
}

Seo.Route/Controllers/EngineersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Seo.Route.Controllers
{
    public class EngineersController : BaseController
    {
        public ActionResult EngineerDetails(int EngineerId, string attributes)
        {
            return View(EngineerId);
        }

        public ActionResult EnginnerDetail(Int32 ID)
        {
            return View(ID);
        }
    }
}

Seo.Route/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Seo.Route.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Error()
        {
            return View();
        }

    }
}

Seo.Route/Views/Engineers/EngineerDetails.cshtml
@model int
@{
    ViewBag.Title = "Seo Route ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Route now  is : </h1>
<br />
<h1> www.Site.com/EngineerName   </h1><br />
<h1>
    - not www.Site.com/Engineers/EngineerDetails?ID=@Model
</h1>
<h2>Parameter value is : @Model</h2>

Seo.Route/Views/Engineers/EnginnerDetail.cshtml
@model int
@{
    ViewBag.Title = "EnginnerDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Route now  is : </h1>
<br />
<h1>
     www.Site.com/Engineers/EngineerDetails?ID=13
</h1>
<h2>Parameter value is : @Model</h2>

Seo.Route/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";

}
<h3>Normal Url   - Domain.com/Controllers/Action?ID=1   .. etc</h3>
<br />
<h3>My Url   -     Domain.com/ParameterName   from db or cache</h3>
<br />
<ul class="nav">
    <li><a href="/Home/Index">Home - http://localhost:51801/Home/Index </a></li>
    <li><a href="@Url.Action("EnginnerDetail","Engineers" , new { ID = 13 })" target="_blank">Normal Url - http://localhost:51801/Engineers/EnginnerDetails?EngineerId=value </a></li>
    <li><a href="@Url.RouteUrl("EngineerSeo1", new RouteValueDictionary { { "SeName", "Eng-Mohamad-Alsaid" } })" target="_blank">Enginner Detail Url - http://localhost:51801/Eng-Mohamad-Alsaid </a></li>
    <li><a href="@Url.RouteUrl("EngineerSeo2", new RouteValueDictionary { { "SeCountry", "Syria" } })" target="_blank">Country - http://localhost:51801/Syria </a></li>
    <li><a href="@Url.RouteUrl("EngineerSeo3", new RouteValueDictionary { { "SeMobile", "0090538972117"} })" target="_blank">Mobile - http://localhost:51801/0090538972117 </a></li>
</ul>

Seo.Route/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/Home/Index">Home</a></li>
                    <li><a href="@Url.Action("EnginnerDetail","Engineers" , new { ID = 13 })" target="_blank">Normal Url</a></li>
                    <li><a href="@Url.RouteUrl("EngineerSeo1", new RouteValueDictionary { { "SeName", "Eng-Mohamad-Alsaid" } })" target="_blank">Enginner Detail Url</a></li>
                    <li><a href="@Url.RouteUrl("EngineerSeo2", new RouteValueDictionary { { "SeCountry", "Syria" } })" target="_blank">Country</a></li>
                    <li><a href="@Url.RouteUrl("EngineerSeo3", new RouteValueDictionary { { "SeMobile", "0090538972117"} })" target="_blank">Mobile</a></li>
                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Eng.Mohamad Khir Alsaid - Syria - mokhear@hotmail.com</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>